import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";

export const metadata: Metadata = {
  title: "UBC Course Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans text-sm flex">
        <Navigation />
        <main className="h-screen overflow-scroll grow p-[20px]">
          {children}
        </main>
      </body>
    </html>
  );
}
