import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";

export const metadata: Metadata = {
  title: "UBC Course Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-md font-sans text-base md:text-lg w-screen h-dvh flex flex-col-reverse gap-md md:flex-row overflow-hidden">
        <Navigation />
        <main className="grow overflow-scroll">{children}</main>
      </body>
    </html>
  );
}
